// Generated by CoffeeScript 1.3.3
(function() {
  var Adventurer;

  Adventurer = (function() {

    Adventurer.prototype.frames = ["north", "east", "south", "west", "content"];

    function Adventurer(options) {
      var _ref, _ref1,
        _this = this;
      this.steps = [];
      this.with_navigation = (_ref = options.with_navigation) != null ? _ref : true;
      this.with_autoplay = (_ref1 = options.with_autoplay) != null ? _ref1 : true;
      this.render();
      this.current_step_index = 0;
      this.frame_size = 10;
      $(window).resize(function() {
        return _this.position_frames();
      });
    }

    Adventurer.prototype.add_step = function(element, text) {
      return this.steps.push({
        "element": element,
        "text": text
      });
    };

    Adventurer.prototype.begin = function() {
      if (this.with_autoplay) {
        console.log("Switching steps automatically");
      } else {
        console.log("Only manual step switch");
      }
      this.show();
      return this.display_step();
    };

    Adventurer.prototype.next_step = function() {
      this.current_step_index++;
      return this.display_step();
    };

    Adventurer.prototype.previous_step = function() {};

    Adventurer.prototype.render = function() {
      var current, frame, _i, _len, _ref;
      _ref = this.frames;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        frame = _ref[_i];
        current = $("<div class='adventurer_frame " + frame + "'></div>").css({
          "opacity": 0.5
        });
        $("body").append(current);
      }
      $(".adventurer_frame.north, .adventurer_frame.south").css({
        "width": document.width
      });
      return this;
    };

    Adventurer.prototype.display_step = function() {
      return this.position_frames();
    };

    Adventurer.prototype.hide = function() {
      $("body").removeClass("with_adventurer");
      return $(".adventurer_frame").css({
        "display": "none"
      });
    };

    Adventurer.prototype.show = function() {
      $("body").addClass("with_adventurer");
      return $(".adventurer_frame").css({
        "display": "block"
      });
    };

    Adventurer.prototype.position_frames = function() {
      var height, left, top, width;
      top = this.current_step().offset().top;
      left = this.current_step().offset().left;
      width = this.current_step().width();
      height = this.current_step().height();
      $(".adventurer_frame.north").animate({
        "height": top - (this.frame_size / 2),
        "width": document.width
      });
      $(".adventurer_frame.south").animate({
        "height": document.height - height - top - (this.frame_size / 2),
        "width": document.width
      });
      $(".adventurer_frame.west").animate({
        "top": top - (this.frame_size / 2),
        "width": left - (this.frame_size / 2),
        "height": height + this.frame_size
      });
      $(".adventurer_frame.east").animate({
        "top": top - (this.frame_size / 2),
        "width": left - (this.frame_size / 2),
        "height": height + this.frame_size
      });
      return $(".adventurer_frame.content").animate({
        "top": top - (this.frame_size / 2),
        "left": left - (this.frame_size / 2),
        "width": width + this.frame_size - 1,
        "height": height + this.frame_size - 1
      });
    };

    Adventurer.prototype.current_step = function() {
      return $(this.steps[this.current_step_index].element);
    };

    Adventurer.prototype.initialize_view = function() {};

    Adventurer.prototype.render_navigation = function() {};

    return Adventurer;

  })();

  window.Adventurer = Adventurer;

}).call(this);
