// Generated by CoffeeScript 1.3.3
(function() {
  var Adventurer;

  jQuery.easing.def = "easeInOutQuint";

  Adventurer = (function() {

    Adventurer.prototype.frames = ["content"];

    function Adventurer(options) {
      var _ref, _ref1,
        _this = this;
      this.steps = [];
      this.with_navigation = (_ref = options.with_navigation) != null ? _ref : true;
      this.with_autoplay = (_ref1 = options.with_autoplay) != null ? _ref1 : true;
      this.render();
      this.current_step_index = 0;
      this.frame_size = 10;
      this.default_delay = 2000;
      $(window).resize(function() {
        return _this.position_frames();
      });
      $(window).keyup(function(event) {
        if (event.keyCode === 32 || event.keyCode === 39) {
          if (_this.current_step_index < _this.steps.length - 1) {
            return _this.next_step();
          }
        } else if (event.keyCode === 37) {
          if (_this.current_step_index > 0) {
            return _this.previous_step();
          }
        }
      });
    }

    Adventurer.prototype.add_step = function(element, text) {
      return this.steps.push({
        "element": element,
        "text": text
      });
    };

    Adventurer.prototype.begin = function() {
      var _this = this;
      this.show();
      this.display_step();
      if (this.with_autoplay) {
        return this.pid = setInterval(function() {
          if (_this.current_step_index < _this.steps.length - 1) {
            return _this.next_step();
          } else {
            clearInterval(_this.pid);
            return _this.pid = null;
          }
        }, this.default_delay);
      }
    };

    Adventurer.prototype.next_step = function() {
      this.current_step_index++;
      return this.display_step();
    };

    Adventurer.prototype.previous_step = function() {
      this.current_step_index--;
      return this.display_step();
    };

    Adventurer.prototype.render = function() {
      var current, frame, _i, _len, _ref;
      _ref = this.frames;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        frame = _ref[_i];
        current = $("<div class='adventurer_frame " + frame + "'></div>").css({
          "opacity": 0.5
        });
        $("body").append(current);
      }
      $(".adventurer_frame.north, .adventurer_frame.south").css({
        "width": document.width
      });
      return this;
    };

    Adventurer.prototype.display_step = function() {
      return this.position_frames();
    };

    Adventurer.prototype.hide = function() {
      $("body").removeClass("with_adventurer");
      return $(".adventurer_frame").css({
        "display": "none"
      });
    };

    Adventurer.prototype.show = function() {
      $("body").addClass("with_adventurer");
      return $(".adventurer_frame").css({
        "display": "block"
      });
    };

    Adventurer.prototype.position_frames = function() {
      var b_bottom, b_left, b_right, b_top, height, left, top, width, window_height, window_width;
      window_width = $(window).width();
      window_height = $(window).height();
      top = this.current_step().offset().top;
      left = this.current_step().offset().left;
      width = this.current_step().width();
      height = this.current_step().height();
      b_top = top;
      b_bottom = window_height - (top + height);
      b_right = window_width - (left + width);
      b_left = left;
      return $(".adventurer_frame.content").stop().animate({
        "border-top-width": b_top,
        "border-bottom-width": b_bottom,
        "border-left-width": b_left,
        "border-right-width": b_right,
        "top": top - (this.frame_size / 2) - b_top,
        "left": left - (this.frame_size / 2) - b_left,
        "width": width + this.frame_size - 1,
        "height": height + this.frame_size - 1
      });
    };

    Adventurer.prototype.animate_step = function(time, steps) {
      var one_step;
      return one_step = time / steps;
    };

    Adventurer.prototype.current_step = function() {
      return $(this.steps[this.current_step_index].element);
    };

    Adventurer.prototype.initialize_view = function() {};

    Adventurer.prototype.render_navigation = function() {};

    return Adventurer;

  })();

  window.Adventurer = Adventurer;

}).call(this);
